### ISSUE TITLE
Missing UID in VEvent elements in the generate calendar

### ISSUE THREAD

**Issue by cristianolongo** [opendatahacklab/agenda-unica#56]
Th UID field is empty. Check in the specification if the event IRI can be used as event UID

**Comment by fedefra** [comment]
For UID field can be used everything which guarantees persistent, globally unique identifier for the calendar component.
I was thinking something as indicate in the RFC : "date-create(text format)@agenda-unica" but we can use IRI too.

**Comment by cristianolongo** [comment]
The URI of the individual representing the event (it should be ?item) is a
unique identifier for the event in the universe.

**Comment by fedefra** [comment]
Update done using URI for UID.

**Comment by fedefra** [comment]
Use the URI for UID generate a warning in the RFC 5545 validator because the strings are too long

**Comment by cristianolongo** [comment]
it has to be split as indicated in the RFC itself. I think this fix should be propagated to other fields.
